// Code generated by protoc-gen-go.
// source: authorization/authorization.proto
// DO NOT EDIT!

package authorization

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

// Input object
type ID struct {
	// Unique identifier for permissions
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ID) Reset()                    { *m = ID{} }
func (m *ID) String() string            { return proto.CompactTextString(m) }
func (*ID) ProtoMessage()               {}
func (*ID) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type Permission struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Permission) Reset()                    { *m = Permission{} }
func (m *Permission) String() string            { return proto.CompactTextString(m) }
func (*Permission) ProtoMessage()               {}
func (*Permission) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type Permissions struct {
	Values []*Permission `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *Permissions) Reset()                    { *m = Permissions{} }
func (m *Permissions) String() string            { return proto.CompactTextString(m) }
func (*Permissions) ProtoMessage()               {}
func (*Permissions) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *Permissions) GetValues() []*Permission {
	if m != nil {
		return m.Values
	}
	return nil
}

type AlterPermissionsRequest struct {
	Names []string `protobuf:"bytes,1,rep,name=names" json:"names,omitempty"`
}

func (m *AlterPermissionsRequest) Reset()                    { *m = AlterPermissionsRequest{} }
func (m *AlterPermissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*AlterPermissionsRequest) ProtoMessage()               {}
func (*AlterPermissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

type Role struct {
	Id        string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	CreatedAt string `protobuf:"bytes,3,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt string `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
}

func (m *Role) Reset()                    { *m = Role{} }
func (m *Role) String() string            { return proto.CompactTextString(m) }
func (*Role) ProtoMessage()               {}
func (*Role) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

type Roles struct {
	Values []*Role `protobuf:"bytes,1,rep,name=values" json:"values,omitempty"`
}

func (m *Roles) Reset()                    { *m = Roles{} }
func (m *Roles) String() string            { return proto.CompactTextString(m) }
func (*Roles) ProtoMessage()               {}
func (*Roles) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Roles) GetValues() []*Role {
	if m != nil {
		return m.Values
	}
	return nil
}

type PermissionsToRoleRequest struct {
	RoleId        string   `protobuf:"bytes,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	PermissionIds []string `protobuf:"bytes,2,rep,name=permission_ids,json=permissionIds" json:"permission_ids,omitempty"`
}

func (m *PermissionsToRoleRequest) Reset()                    { *m = PermissionsToRoleRequest{} }
func (m *PermissionsToRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*PermissionsToRoleRequest) ProtoMessage()               {}
func (*PermissionsToRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

type RolesToPermissionRequest struct {
	PermissionId string   `protobuf:"bytes,1,opt,name=permission_id,json=permissionId" json:"permission_id,omitempty"`
	RoleIds      []string `protobuf:"bytes,2,rep,name=role_ids,json=roleIds" json:"role_ids,omitempty"`
}

func (m *RolesToPermissionRequest) Reset()                    { *m = RolesToPermissionRequest{} }
func (m *RolesToPermissionRequest) String() string            { return proto.CompactTextString(m) }
func (*RolesToPermissionRequest) ProtoMessage()               {}
func (*RolesToPermissionRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

type RolesToUserRequest struct {
	UserId  string   `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	RoleIds []string `protobuf:"bytes,2,rep,name=role_ids,json=roleIds" json:"role_ids,omitempty"`
}

func (m *RolesToUserRequest) Reset()                    { *m = RolesToUserRequest{} }
func (m *RolesToUserRequest) String() string            { return proto.CompactTextString(m) }
func (*RolesToUserRequest) ProtoMessage()               {}
func (*RolesToUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{9} }

type UsersToRoleRequest struct {
	RoleId  string   `protobuf:"bytes,1,opt,name=role_id,json=roleId" json:"role_id,omitempty"`
	UserIds []string `protobuf:"bytes,2,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
}

func (m *UsersToRoleRequest) Reset()                    { *m = UsersToRoleRequest{} }
func (m *UsersToRoleRequest) String() string            { return proto.CompactTextString(m) }
func (*UsersToRoleRequest) ProtoMessage()               {}
func (*UsersToRoleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{10} }

type AuthorizeRequest struct {
	UserId string `protobuf:"bytes,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Method string `protobuf:"bytes,2,opt,name=method" json:"method,omitempty"`
}

func (m *AuthorizeRequest) Reset()                    { *m = AuthorizeRequest{} }
func (m *AuthorizeRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthorizeRequest) ProtoMessage()               {}
func (*AuthorizeRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{11} }

func init() {
	proto.RegisterType((*Empty)(nil), "authorization.Empty")
	proto.RegisterType((*ID)(nil), "authorization.ID")
	proto.RegisterType((*Permission)(nil), "authorization.Permission")
	proto.RegisterType((*Permissions)(nil), "authorization.Permissions")
	proto.RegisterType((*AlterPermissionsRequest)(nil), "authorization.AlterPermissionsRequest")
	proto.RegisterType((*Role)(nil), "authorization.Role")
	proto.RegisterType((*Roles)(nil), "authorization.Roles")
	proto.RegisterType((*PermissionsToRoleRequest)(nil), "authorization.PermissionsToRoleRequest")
	proto.RegisterType((*RolesToPermissionRequest)(nil), "authorization.RolesToPermissionRequest")
	proto.RegisterType((*RolesToUserRequest)(nil), "authorization.RolesToUserRequest")
	proto.RegisterType((*UsersToRoleRequest)(nil), "authorization.UsersToRoleRequest")
	proto.RegisterType((*AuthorizeRequest)(nil), "authorization.AuthorizeRequest")
}

func init() { proto.RegisterFile("authorization/authorization.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 365 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xbc, 0x93, 0x5f, 0x4b, 0xc3, 0x30,
	0x14, 0xc5, 0x59, 0xb7, 0x75, 0xdb, 0x9d, 0x1b, 0x12, 0x87, 0xeb, 0x1e, 0x84, 0x19, 0x11, 0x06,
	0xc2, 0x86, 0x7f, 0x3e, 0x80, 0x45, 0x05, 0xf7, 0x26, 0x65, 0xbe, 0xf8, 0x32, 0xaa, 0xb9, 0xb0,
	0x42, 0xdb, 0xd4, 0x24, 0x15, 0xf4, 0xd3, 0x4b, 0xd2, 0xac, 0x6b, 0xf7, 0x32, 0x9f, 0x7c, 0xeb,
	0xbd, 0x27, 0xfd, 0x9d, 0x73, 0x42, 0x0b, 0xe7, 0x61, 0xae, 0x36, 0x5c, 0x44, 0x3f, 0xa1, 0x8a,
	0x78, 0xba, 0xa8, 0x4d, 0xf3, 0x4c, 0x70, 0xc5, 0xc9, 0xa0, 0xb6, 0xa4, 0x1d, 0x68, 0x3f, 0x25,
	0x99, 0xfa, 0xa6, 0x23, 0x70, 0x96, 0x8f, 0x64, 0x08, 0x4e, 0xc4, 0xbc, 0xc6, 0xb4, 0x31, 0xeb,
	0x05, 0x4e, 0xc4, 0x68, 0x0a, 0xf0, 0x82, 0x22, 0x89, 0xa4, 0x8c, 0x78, 0xba, 0xaf, 0x12, 0x02,
	0xad, 0x34, 0x4c, 0xd0, 0x73, 0xcc, 0xc6, 0x3c, 0x93, 0x33, 0x80, 0x0f, 0x81, 0xa1, 0x42, 0xb6,
	0x0e, 0x95, 0xd7, 0x34, 0x4a, 0xcf, 0x6e, 0x7c, 0xa5, 0xe5, 0x3c, 0x63, 0x5b, 0xb9, 0x55, 0xc8,
	0x76, 0xe3, 0x2b, 0x7a, 0x0f, 0xfd, 0x9d, 0x9f, 0x24, 0xd7, 0xe0, 0x7e, 0x85, 0x71, 0x8e, 0xd2,
	0x6b, 0x4c, 0x9b, 0xb3, 0xfe, 0xcd, 0x64, 0x5e, 0xaf, 0xb4, 0x3b, 0x1b, 0xd8, 0x83, 0x74, 0x01,
	0x63, 0x3f, 0x56, 0x28, 0x2a, 0x98, 0x00, 0x3f, 0x73, 0x94, 0x8a, 0x8c, 0xa0, 0xad, 0x23, 0x16,
	0xb0, 0x5e, 0x50, 0x0c, 0x74, 0x03, 0xad, 0x80, 0xc7, 0xf8, 0x0f, 0xe5, 0xee, 0xa0, 0xad, 0x9d,
	0x24, 0xb9, 0xda, 0xab, 0x75, 0xb2, 0x57, 0x4b, 0x9f, 0x2a, 0x0b, 0xbd, 0x81, 0x57, 0xe9, 0xb2,
	0xe2, 0x46, 0xb4, 0x8d, 0xc6, 0xd0, 0x11, 0x3c, 0xc6, 0x75, 0x19, 0xdc, 0xd5, 0xe3, 0x92, 0x91,
	0x4b, 0x18, 0x66, 0xe5, 0x4b, 0xeb, 0x88, 0x49, 0xcf, 0x31, 0x9d, 0x07, 0xbb, 0xed, 0x92, 0x19,
	0xb6, 0x49, 0xb4, 0xe2, 0x95, 0x9b, 0xb4, 0xec, 0x0b, 0x18, 0xd4, 0x10, 0xd6, 0xe1, 0xa8, 0x4a,
	0x20, 0x13, 0xe8, 0xda, 0x00, 0x5b, 0x87, 0x4e, 0x91, 0x40, 0xd2, 0x67, 0x20, 0x96, 0xfd, 0x2a,
	0x51, 0x54, 0x12, 0xe7, 0x12, 0x45, 0x25, 0xb1, 0x1e, 0x0f, 0x92, 0x34, 0xe2, 0xaf, 0xdd, 0x27,
	0xd0, 0xb5, 0x16, 0x25, 0xa9, 0xf0, 0x90, 0xf4, 0x01, 0x8e, 0x7d, 0x7b, 0xd3, 0x78, 0x30, 0xd1,
	0x29, 0xb8, 0x09, 0xaa, 0x0d, 0x67, 0xf6, 0x13, 0xb0, 0xd3, 0xbb, 0x6b, 0x7e, 0xa4, 0xdb, 0xdf,
	0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0xff, 0x42, 0xac, 0x6d, 0x03, 0x00, 0x00,
}
